stages:
  - deploy

### deploy playbook with manual run
deploy:
  stage: deploy
  image: registry.gitlab.com/torese/docker-ansible
  before_script:
  - ansible --version
  - mkdir secret
  - echo "$RUNNER_PRIVATE_KEY" > secret/ansible.key
  - export ANSIBLE_HOST_KEY_CHECKING=False
  script:
    - ansible all -m ping -v --private-key secret/ansible.key --u ubuntu -i inventori.ini
  tags:
    - ansible
  when: manual

#   - ansible-playbook --private-key secret/ansible.key --user ubuntu -i inventori.ini setup-redis-sentinel.yml

