---

### use fedora image with pre-installed ansible and python
image: registry.sirius.online/infra/redis/docker-ansible:v0.0.1

### copy runner's private key into image
before_script:
  - ansible --version
  - mkdir secret
  - echo "$RUNNER_PRIVATE_KEY" > secret/ansible.key
  - export ANSIBLE_HOST_KEY_CHECKING=False

stages:
  - deploy

### deploy playbook with manual run
deploy:
  stage: deploy
  script:
    - ansible-playbook --private-key secret/ansible.key --user ubuntu -i inventory.ini setup-redis-sentinel.yml
  tags:
    - ansible
  when: manual
